extends Node


enum SCENE {MAINMENU, ACTIONPHASE}
@export var SCENE_PATH : Dictionary = {
	SCENE.MAINMENU: "res://Scenes/MainMenu.tscn",
	SCENE.ACTIONPHASE: "res://Scenes/ActionPhase.tscn",
}

enum CONFIG_GAME_PARAMS {ALL_CONTENTS, CONTENTS_AVAILABLE, SESSION_CONTENTS, SESSION_USED_CONTENTS}
